# Generated by Django 5.2.11 on 2026-04-05 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_messaging_thread_org_and_message_fields'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='core.organisation'),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('org_shared', 'Organisation team thread')], db_index=True, default='direct', max_length=20),
        ),
    ]
