# Generated by Django 5.2.11 on 2026-03-09 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_backfill_submission_status_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('initial_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('initial_notes', models.TextField(blank=True)),
                ('final_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('final_terms', models.TextField(blank=True, help_text='Final accepted terms summary')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_detail', to='submissions.applicationsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('bonus_notes', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='submissions.offer')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
