# Generated by Django 5.2.11 on 2026-03-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_offer_negotiation_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('from_address', models.EmailField(max_length=255)),
                ('to_address', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_snippet', models.TextField(blank=True)),
                ('raw_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('detected_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('IN_PROGRESS', 'In Progress'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected')], default='UNKNOWN', max_length=20)),
                ('detected_candidate_name', models.CharField(blank=True, max_length=255)),
                ('detected_company', models.CharField(blank=True, max_length=255)),
                ('detected_job_title', models.CharField(blank=True, max_length=255)),
                ('confidence', models.PositiveSmallIntegerField(default=0)),
                ('applied_action', models.CharField(choices=[('none', 'No Action'), ('auto_updated', 'Auto Updated'), ('needs_review', 'Needs Review')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_events', to='submissions.applicationsubmission')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
    ]
