# Generated by Django 5.2.11 on 2026-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_email_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailevent',
            name='applied_action',
            field=models.CharField(choices=[('none', 'No Action'), ('auto_updated', 'Auto Updated'), ('needs_review', 'Needs Review'), ('manual_updated', 'Manually Updated')], default='none', max_length=20),
        ),
    ]
