# Generated by Django 5.2.11 on 2026-04-04 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_email_event_manual_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Received'), ('PLACED', 'Placed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='APPLIED', max_length=20),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('CONTRACT_TO_HIRE', 'Contract-to-Hire'), ('TEMPORARY', 'Temporary')], default='PERMANENT', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated Early'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(help_text='Placement start date')),
                ('end_date', models.DateField(blank=True, help_text='Placement end date (for contracts)', null=True)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly bill rate to client', max_digits=10, null=True)),
                ('pay_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly pay rate to consultant', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('fee_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Placement fee as % of annual salary (permanent placements)', max_digits=5, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Flat placement fee amount', max_digits=12, null=True)),
                ('annual_salary', models.DecimalField(blank=True, decimal_places=2, help_text="Consultant's annual salary (for permanent placements)", max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placements', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement', to='submissions.applicationsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate as % of placement revenue', max_digits=5, null=True)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Calculated or overridden commission amount', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee who earned the commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='submissions.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending', models.DateField(help_text='Saturday of the work week')),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Total hours worked this week', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours (included in hours_worked)', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='submissions.placement')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_timesheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_ending'],
                'unique_together': {('placement', 'week_ending')},
            },
        ),
    ]
