# Generated by Django 5.2.13 on 2026-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_add_source_to_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubmission',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interview Scheduled'), ('OFFER', 'Offer Received'), ('PLACED', 'Placed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='APPLIED', max_length=20),
        ),
    ]
