# Generated by Django 5.2.11 on 2026-02-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_last_edited_at_job_last_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parsed_jd',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_jd_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_jd_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_jd_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
