# Generated by Django 5.2.11 on 2026-03-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('jobs', '0009_job_parsed_jd_job_parsed_jd_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_obj',
            field=models.ForeignKey(blank=True, help_text='Structured company profile backing this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(help_text='Legacy company name (will be kept for compatibility).', max_length=200),
        ),
    ]
