# Generated by Django 5.2.11 on 2026-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_add_company_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='original_link_is_live',
            field=models.BooleanField(default=True, help_text='Set via background checker. False when the original job URL appears to be gone.'),
        ),
        migrations.AddField(
            model_name='job',
            name='original_link_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='possibly_filled',
            field=models.BooleanField(default=False, help_text='Flag set when the job URL starts returning 4xx/410; suggests the role might be filled or closed externally.'),
        ),
    ]
