# Generated by Django 5.2.11 on 2026-04-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_url_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-deleted / archived'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_source',
            field=models.CharField(blank=True, help_text='Where this job was found (e.g. LinkedIn, Indeed, Referral, Website)', max_length=100),
        ),
    ]
