# Generated by Django 5.2.13 on 2026-04-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_validation_pipeline'),
        ('users', '0022_phase2_3_embeddings_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='Embedding float list from text-embedding-3-small')),
                ('model', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Embedding',
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Cosine similarity 0.0–1.0')),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Rank among all consultants for this job (1 = best)')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='users.consultantprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Match Score',
                'ordering': ['rank'],
                'unique_together': {('job', 'consultant')},
            },
        ),
    ]
