# Generated by Django 5.2.13 on 2026-04-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_phase2_3_embeddings_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quality_score',
            field=models.FloatField(blank=True, help_text='0.0–1.0 fraction of key fields populated.', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('DISCOVERED', 'Discovered'), ('FETCHED', 'Fetched'), ('ENRICHED', 'Enriched'), ('SCORED', 'Scored'), ('VETTED', 'Vetted'), ('LIVE', 'Live'), ('MATCHED', 'Matched'), ('FILLED', 'Filled'), ('ARCHIVED', 'Archived')], db_index=True, default='DISCOVERED', help_text='Unified pipeline stage — supersedes status over time.', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stage_owner',
            field=models.ForeignKey(blank=True, help_text='Staffer responsible at current stage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 of original_link for cross-platform dedupe.', max_length=64),
        ),
        migrations.CreateModel(
            name='PipelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(blank=True, db_index=True, help_text='Allows event logging before Job row exists.', max_length=64)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(blank=True, max_length=20)),
                ('task_name', models.CharField(blank=True, max_length=120)),
                ('celery_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('RUNNING', 'Running')], default='SUCCESS', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Task-specific payload.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, help_text='Nullable: pre-FETCHED events (discovery) may not have a Job yet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_events', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Pipeline Event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['job', '-occurred_at'], name='jobs_pipeli_job_id_73db24_idx'), models.Index(fields=['to_stage', '-occurred_at'], name='jobs_pipeli_to_stag_7a2d12_idx'), models.Index(fields=['status', '-occurred_at'], name='jobs_pipeli_status_f10d45_idx')],
            },
        ),
    ]
