# Generated by Django 5.2.13 on 2026-06-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_job_auto_marketing_role_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship')], db_index=True, default='FULL_TIME', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('POOL', 'In Pool'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('DRAFT', 'Draft')], db_index=True, default='POOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='url_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA256 of original_link for cross-platform dedupe. Unique when non-empty.', max_length=64),
        ),
    ]
