# Generated by Django 5.2.13 on 2026-06-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_db_optimization_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='original_link_final_url',
            field=models.URLField(blank=True, default='', help_text='Resolved URL after redirects during the last link-health check.', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='original_link_health',
            field=models.CharField(choices=[('LIVE', 'Live'), ('INCONCLUSIVE', 'Inconclusive'), ('DEAD', 'Dead')], db_index=True, default='LIVE', help_text='Tri-state source link health: LIVE, INCONCLUSIVE, or DEAD.', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='original_link_reason',
            field=models.CharField(blank=True, default='', help_text='Last link-health reason code from the checker.', max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='original_link_status_code',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Last HTTP status code observed during the link-health check.', null=True),
        ),
    ]
