# Generated by Django 5.2.13 on 2026-06-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_original_link_final_url_job_original_link_health_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parsed_jd_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_jd_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_jd_prompt_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='parsed_jd_schema_version',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
