# Generated by Django 5.2.13 on 2026-06-16 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0067_remote_llm_jd_scan'),
        ('jobs', '0022_jd_extractor_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawJobClassifierRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('backend_rules', 'Backend Rules'), ('codex', 'Codex'), ('claude', 'Claude'), ('secondary_stub', 'Secondary Stub')], db_index=True, max_length=32)),
                ('provider_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], db_index=True, default='PRIMARY', max_length=12)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('provider_version', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], db_index=True, default='QUEUED', max_length=12)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_output', models.JSONField(blank=True, default=dict)),
                ('normalized_output', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_runs', to='harvest.rawjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawJobClassificationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_input_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('MERGED', 'Merged'), ('NEEDS_REVIEW', 'Needs Review'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('merged_output', models.JSONField(blank=True, default=dict)),
                ('verifier_summary', models.JSONField(blank=True, default=dict)),
                ('final_confidence', models.FloatField(default=0.0)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('review_reason', models.CharField(blank=True, max_length=120)),
                ('ready_for_vetting', models.BooleanField(db_index=True, default=False)),
                ('last_merged_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_snapshot', to='harvest.rawjob')),
                ('backend_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.rawjobclassifierrun')),
                ('secondary_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.rawjobclassifierrun')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RawJobClassificationConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_path', models.CharField(db_index=True, max_length=120)),
                ('backend_value', models.JSONField(blank=True, null=True)),
                ('secondary_value', models.JSONField(blank=True, null=True)),
                ('resolved_value', models.JSONField(blank=True, null=True)),
                ('resolution', models.CharField(choices=[('AGREED', 'Agreed'), ('BACKEND', 'Backend Wins'), ('SECONDARY', 'Secondary Wins'), ('MANUAL', 'Manual Override'), ('REVIEW', 'Needs Review')], db_index=True, default='REVIEW', max_length=16)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warn'), ('CRITICAL', 'Critical')], db_index=True, default='WARN', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_conflicts', to='harvest.rawjob')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conflicts', to='jobs.rawjobclassificationsnapshot')),
            ],
            options={
                'ordering': ['field_path', 'id'],
                'indexes': [models.Index(fields=['raw_job', 'field_path'], name='jobs_rawjob_raw_job_625c64_idx'), models.Index(fields=['resolution', 'severity'], name='jobs_rawjob_resolut_16b670_idx')],
                'unique_together': {('snapshot', 'field_path')},
            },
        ),
        migrations.AddIndex(
            model_name='rawjobclassifierrun',
            index=models.Index(fields=['raw_job', 'provider', '-created_at'], name='jobs_rawjob_raw_job_7cbb9d_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobclassifierrun',
            index=models.Index(fields=['raw_job', 'provider_role', '-created_at'], name='jobs_rawjob_raw_job_25d6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobclassifierrun',
            index=models.Index(fields=['status', '-created_at'], name='jobs_rawjob_status_1167d3_idx'),
        ),
        migrations.AddIndex(
            model_name='rawjobclassifierrun',
            index=models.Index(fields=['input_hash', 'provider', '-created_at'], name='jobs_rawjob_input_h_af1f88_idx'),
        ),
    ]
