# Generated by Django 5.2.13 on 2026-06-16 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_rawjobclassifierrun_rawjobclassificationsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approval_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approval_state',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('APPROVED', 'Approved'), ('OVERRIDDEN', 'Overridden')], db_index=True, default='UNREVIEWED', max_length=16),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rawjob_classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approved_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approved_source',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
