# Generated by Django 5.2.13 on 2026-06-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_rawjobclassificationsnapshot_approval_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='pushed_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawjob_classification_pushes', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='pushed_to_vetting_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='pushed_to_vetting_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushed_rawjob_classifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='pushed_to_vetting_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='pushed_to_vetting_with_warnings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='pushed_warning_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
