# Generated by Django 5.2.13 on 2026-06-18 00:43

import hashlib
import json

from django.db import migrations, models


def _stable_json(data):
    return json.dumps(data, sort_keys=True, separators=(",", ":"), ensure_ascii=True, default=str)


def _approval_input_for_raw_job(raw_job):
    return {
        "raw_job_id": raw_job.pk,
        "platform_slug": getattr(raw_job, "platform_slug", "") or "",
        "original_url": getattr(raw_job, "original_url", "") or "",
        "apply_url": getattr(raw_job, "apply_url", "") or "",
        "title": getattr(raw_job, "title", "") or "",
        "description": getattr(raw_job, "description", "") or "",
        "description_clean": getattr(raw_job, "description_clean", "") or "",
        "description_raw_html": getattr(raw_job, "description_raw_html", "") or "",
        "has_html_content": bool(getattr(raw_job, "has_html_content", False)),
        "cleaning_version": getattr(raw_job, "cleaning_version", "") or "",
        "requirements": getattr(raw_job, "requirements", "") or "",
        "responsibilities": getattr(raw_job, "responsibilities", "") or "",
        "benefits": getattr(raw_job, "benefits", "") or "",
        "department": getattr(raw_job, "department", "") or "",
        "location_raw": getattr(raw_job, "location_raw", "") or "",
        "city": getattr(raw_job, "city", "") or "",
        "state": getattr(raw_job, "state", "") or "",
        "country": getattr(raw_job, "country", "") or "",
        "country_codes": list(getattr(raw_job, "country_codes", None) or []),
        "location_candidates": list(getattr(raw_job, "location_candidates", None) or []),
        "vendor_location_block": getattr(raw_job, "vendor_location_block", "") or "",
        "employment_type": getattr(raw_job, "employment_type", "") or "",
        "experience_level": getattr(raw_job, "experience_level", "") or "",
        "salary_raw": getattr(raw_job, "salary_raw", "") or "",
        "company_name": getattr(raw_job, "company_name", "") or "",
        "posted_date": str(getattr(raw_job, "posted_date", "") or ""),
        "vendor_degree_level": getattr(raw_job, "vendor_degree_level", "") or "",
        "vendor_job_schedule": getattr(raw_job, "vendor_job_schedule", "") or "",
        "vendor_job_shift": getattr(raw_job, "vendor_job_shift", "") or "",
        "vendor_job_category": getattr(raw_job, "vendor_job_category", "") or "",
        "vendor_job_identification": getattr(raw_job, "vendor_job_identification", "") or "",
        "location_type": getattr(raw_job, "location_type", "") or "",
        "is_remote": bool(getattr(raw_job, "is_remote", False)),
        "role_category": getattr(raw_job, "role_category", "") or "",
        "country_code": getattr(raw_job, "country_code", "") or "",
        "scope_status": getattr(raw_job, "scope_status", "") or "",
    }


def backfill_approval_input_hash(apps, schema_editor):
    Snapshot = apps.get_model("jobs", "RawJobClassificationSnapshot")
    for snapshot in Snapshot.objects.select_related("raw_job").exclude(approved_output={}).iterator(chunk_size=200):
        raw_job = getattr(snapshot, "raw_job", None)
        if not raw_job:
            continue
        payload = _approval_input_for_raw_job(raw_job)
        snapshot.approval_input_hash = hashlib.sha256(_stable_json(payload).encode("utf-8")).hexdigest()
        snapshot.save(update_fields=["approval_input_hash"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_rawjobclassificationsnapshot_pushed_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approval_input_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approval_is_stale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approval_stale_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_approval_input_hash, migrations.RunPython.noop),
    ]
