# Generated by Django 5.2.13 on 2026-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_rawjobclassificationsnapshot_approval_input_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='routing_clearance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_country_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_country_mode',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_extracted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_override',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_override_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_prompt_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_role_family',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_schema_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_seniority',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_source',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('REVIEW', 'Needs Review'), ('FAILED', 'Failed'), ('OVERRIDDEN', 'Overridden')], db_index=True, default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_visa_sponsorship',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_warnings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_work_authorization',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_work_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_years_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_years_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
