# Generated by Django 5.2.13 on 2026-06-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_job_routing_clearance_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='routing_employment_terms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='routing_work_auth_category',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
