# Generated by Django 5.2.13 on 2026-06-28 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_job_routing_employment_terms_and_more'),
        ('users', '0030_employeraccessrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='primary_marketing_role',
            field=models.ForeignKey(blank=True, help_text='Single downstream marketing role used for consultant routing and resume targeting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_jobs', to='users.marketingrole'),
        ),
        migrations.AddField(
            model_name='job',
            name='primary_marketing_role_locked',
            field=models.BooleanField(default=False, help_text='When enabled, automatic refreshes cannot overwrite the primary marketing role.'),
        ),
        migrations.AddField(
            model_name='job',
            name='primary_marketing_role_source',
            field=models.CharField(blank=True, default='', help_text='How the primary role was chosen: auto, approved_snapshot, manual_override.', max_length=24),
        ),
        migrations.AddField(
            model_name='job',
            name='primary_marketing_role_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='approved_primary_role_slug',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='primary_role_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='primary_role_overridden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='primary_role_overridden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_rawjob_primary_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='primary_role_override_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rawjobclassificationsnapshot',
            name='primary_role_source',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
