from django.urls import path

from .views import (
    CompanyListView,
    CompanyDetailView,
    CompanyCreateView,
    CompanyUpdateView,
    CompanyExportCSVView,
    CompanySavedViewCreateView,
    CompanySavedViewDefaultView,
    CompanySavedViewDeleteView,
    CompanySavedViewManageView,
    CompanyBulkActionView,
    CompanyQuickActionView,
    CompanyDuplicateReviewView,
    CompanyMergeView,
    CompanyDismissReviewView,
    CompanyCSVImportView,
    CompanyDomainImportView,
    CompanyLinkedInImportView,
    CompanyIntelligenceView,
    CompanySearchView,
    CompanyReEnrichView,
    CompanyQuickFillView,
    CompanyEnrichmentStatusView,
    CompanyCreateAPIView,
    EnrichmentLogListView,
)


urlpatterns = [
    path("", CompanyListView.as_view(), name="company-list"),
    path("new/", CompanyCreateView.as_view(), name="company-create"),
    path("export/", CompanyExportCSVView.as_view(), name="company-export-csv"),
    path("saved-views/new/", CompanySavedViewCreateView.as_view(), name="company-saved-view-create"),
    path("saved-views/<int:pk>/default/", CompanySavedViewDefaultView.as_view(), name="company-saved-view-default"),
    path("saved-views/<int:pk>/manage/", CompanySavedViewManageView.as_view(), name="company-saved-view-manage"),
    path("saved-views/<int:pk>/delete/", CompanySavedViewDeleteView.as_view(), name="company-saved-view-delete"),
    path("bulk-action/", CompanyBulkActionView.as_view(), name="company-bulk-action"),
    path("<int:pk>/quick-action/", CompanyQuickActionView.as_view(), name="company-quick-action"),
    path("import/csv/", CompanyCSVImportView.as_view(), name="company-import-csv"),
    path("import/domains/", CompanyDomainImportView.as_view(), name="company-import-domains"),
    path("import/linkedin/", CompanyLinkedInImportView.as_view(), name="company-import-linkedin"),
    path("search/", CompanySearchView.as_view(), name="company-search"),
    path("api/create/", CompanyCreateAPIView.as_view(), name="company-api-create"),
    path("duplicates/", CompanyDuplicateReviewView.as_view(), name="company-duplicate-review"),
    path("merge/", CompanyMergeView.as_view(), name="company-merge"),
    path("dismiss-review/<int:pk>/", CompanyDismissReviewView.as_view(), name="company-dismiss-review"),
    path("enrichment/", CompanyEnrichmentStatusView.as_view(), name="company-enrichment-status"),
    path("enrichment/logs/", EnrichmentLogListView.as_view(), name="company-enrichment-logs"),
    path("<int:pk>/", CompanyDetailView.as_view(), name="company-detail"),
    path("<int:pk>/intelligence/", CompanyIntelligenceView.as_view(), name="company-intelligence"),
    path("<int:pk>/re-enrich/", CompanyReEnrichView.as_view(), name="company-re-enrich"),
    path("<int:pk>/quick-fill/", CompanyQuickFillView.as_view(), name="company-quick-fill"),
    path("<int:pk>/edit/", CompanyUpdateView.as_view(), name="company-edit"),
]
