# Generated by Django 5.2.11 on 2026-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_llmconfig_prompt_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='match_jd_title_default',
            field=models.BooleanField(default=False, help_text='If enabled, the most recent resume role title is replaced with the JD title by default.'),
        ),
    ]
