# Generated by Django 5.2.11 on 2026-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organisation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='email_imap_encrypted_password',
            field=models.TextField(blank=True, help_text='Encrypted IMAP password or app password (stored encrypted).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_imap_host',
            field=models.CharField(blank=True, default='imap.gmail.com', help_text='IMAP server hostname (e.g. imap.gmail.com).', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_imap_port',
            field=models.IntegerField(default=993, help_text='IMAP port (993 for SSL).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_imap_use_ssl',
            field=models.BooleanField(default=True, help_text='Use SSL/TLS for IMAP connection (recommended).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_imap_username',
            field=models.CharField(blank=True, help_text='IMAP username (usually the email address of the inbox).', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_ingest_enabled',
            field=models.BooleanField(default=False, help_text='Enable IMAP email ingestion for status updates (requires IMAP credentials).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_poll_interval_seconds',
            field=models.IntegerField(default=60, help_text='How often to poll the IMAP inbox for new messages (in seconds).'),
        ),
    ]
