# Generated by Django 5.2.11 on 2026-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_email_ingest_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='email_ai_confidence_threshold',
            field=models.PositiveSmallIntegerField(default=80, help_text='AI confidence threshold (0–100). Only apply AI results at or above this number.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_ai_fallback_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, use AI as a fallback when rules are unsure (token usage).'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_auto_poll_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, a background worker (Celery Beat) will poll IMAP automatically.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_notify_consultant_on_auto_update',
            field=models.BooleanField(default=False, help_text='Send an email to the consultant when an auto-update happens.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='email_notify_employee_on_auto_update',
            field=models.BooleanField(default=False, help_text='Send an email to the employee who submitted the application when an auto-update happens.'),
        ),
    ]
