# Generated by Django 5.2.11 on 2026-03-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_email_ingest_ai_and_autopoll'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Pipeline run log',
                'verbose_name_plural': 'Pipeline run logs',
            },
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='apollo_api_key',
            field=models.CharField(blank=True, help_text='Apollo.io API key for organization enrichment (optional).', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='google_kg_api_key',
            field=models.CharField(blank=True, help_text='Google Knowledge Graph API key for company enrichment (optional).', max_length=255),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='hunter_api_key',
            field=models.CharField(blank=True, help_text='Hunter.io API key for company enrichment (optional).', max_length=255),
        ),
    ]
