# Generated by Django 5.2.11 on 2026-03-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_data_pipeline_api_keys_and_run_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='auto_enrich_on_create',
            field=models.BooleanField(default=True, help_text='When enabled, new companies are automatically queued for enrichment (Clearbit, OG, optional APIs).'),
        ),
    ]
