# Generated by Django 5.2.11 on 2026-04-04 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('kind', models.CharField(choices=[('SUBMISSION', 'Submission'), ('INTERVIEW', 'Interview'), ('JOB', 'Job'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('audience', models.CharField(choices=[('ALL_ACTIVE', 'All active users'), ('STAFF', 'Staff (admins + employees)'), ('CONSULTANTS', 'Consultants only'), ('ADMINS', 'Admins only')], default='ALL_ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, help_text='Optional: limit recipients to this tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('SKIPPED_INAPP', 'Skipped (in-app category off)')], default='DELIVERED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to=settings.AUTH_USER_MODEL)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.broadcastmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['broadcast', 'status'], name='core_broadc_broadca_3e94d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'user'), name='broadcast_delivery_user_uniq')],
            },
        ),
    ]
