# Generated by Django 5.2.11 on 2026-04-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_broadcast_and_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='audience',
            field=models.CharField(choices=[('EMPLOYEES_ONLY', 'Employees only'), ('CONSULTANTS', 'Consultants only'), ('EMPLOYEES_AND_CONSULTANTS', 'Employees and consultants (both)'), ('ALL_ACTIVE', 'Everyone (all active users)'), ('STAFF', 'Staff (admins + employees)'), ('ADMINS', 'Admins only')], default='EMPLOYEES_AND_CONSULTANTS', help_text='Who receives this broadcast (respects optional organisation filter below).', max_length=32),
        ),
    ]
