# Generated by Django 5.2.11 on 2026-04-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_broadcast_audience_workforce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastmessage',
            name='kind',
            field=models.CharField(choices=[('SUBMISSION', 'Submission'), ('INTERVIEW', 'Interview'), ('JOB', 'Job'), ('SYSTEM', 'System'), ('MESSAGE', 'Message')], default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('SUBMISSION', 'Submission'), ('INTERVIEW', 'Interview'), ('JOB', 'Job'), ('SYSTEM', 'System'), ('MESSAGE', 'Message')], default='SYSTEM', max_length=20),
        ),
    ]
