# Generated by Django 5.2.13 on 2026-04-14 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_feature_flags_and_designations(apps, schema_editor):
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    EmployeeDesignation = apps.get_model('core', 'EmployeeDesignation')

    rows = [
        ('consultant_self_apply', 'Self-Apply Tracker', 'Consultants log their own applications.', 'CONSULTANT', 'CONSULTANT', 10),
        ('consultant_my_tracker', 'My Job Tracker', 'Personal application tracker.', 'CONSULTANT', 'CONSULTANT', 20),
        ('consultant_cover_letter', 'Cover Letter AI', 'AI cover letters per job.', 'CONSULTANT', 'BOTH', 30),
        ('consultant_resume_gen', 'Self Resume Generation', 'Consultant self-service resume generation.', 'CONSULTANT', 'CONSULTANT', 40),
        ('consultant_interview_prep', 'Interview Prep AI', 'Prep sheets from JD + profile.', 'CONSULTANT', 'CONSULTANT', 50),
        ('consultant_career_timeline', 'Career Timeline', 'Career timeline view.', 'CONSULTANT', 'CONSULTANT', 60),
        ('consultant_job_matching', 'Job Match Score', 'Match score on job detail.', 'CONSULTANT', 'CONSULTANT', 70),
        ('consultant_public_profile', 'Public Profile', 'Shareable public consultant profile.', 'CONSULTANT', 'CONSULTANT', 80),
        ('consultant_saved_jobs', 'Saved Jobs', 'Bookmark jobs.', 'CONSULTANT', 'CONSULTANT', 90),
        ('consultant_messaging', 'Direct Messaging', 'In-app messaging.', 'CONSULTANT', 'BOTH', 100),
        ('consultant_gdpr_export', 'GDPR Data Export', 'Consultant self-service data export.', 'CONSULTANT', 'CONSULTANT', 110),
        ('employee_job_pool', 'Job Pool Management', 'Staging pool and approvals.', 'EMPLOYEE', 'EMPLOYEE', 200),
        ('employee_bulk_ops', 'Bulk Operations', 'Bulk uploads and status updates.', 'EMPLOYEE', 'EMPLOYEE', 210),
        ('employee_analytics', 'Analytics & Reports', 'Analytics dashboards and win/loss.', 'EMPLOYEE', 'EMPLOYEE', 220),
        ('employee_company_enrich', 'Company Enrichment', 'Company data enrichment tools.', 'EMPLOYEE', 'EMPLOYEE', 230),
        ('employee_workflow', 'Workflow Dashboard', 'Consultant workflow pipeline.', 'EMPLOYEE', 'EMPLOYEE', 240),
        ('employee_csv_export', 'CSV Exports', 'CSV exports for jobs, submissions, etc.', 'EMPLOYEE', 'EMPLOYEE', 250),
        ('employee_impersonate', 'User Impersonation', 'Log in as another user (support).', 'EMPLOYEE', 'EMPLOYEE', 260),
        ('employee_lock_override', 'Override Workflow Lock', 'Take over another user lock on workflow.', 'EMPLOYEE', 'EMPLOYEE', 265),
        ('ai_resume_generation', 'AI Resume Generation', 'LLM resume generation (staff + consultant).', 'AI', 'BOTH', 300),
        ('ai_cover_letter', 'AI Cover Letter', 'LLM cover letter capability.', 'AI', 'BOTH', 310),
        ('ai_interview_prep', 'AI Interview Prep', 'LLM interview prep for staff views.', 'AI', 'BOTH', 320),
        ('ai_rejection_analysis', 'AI Rejection Analysis', 'Rejection coaching / analysis.', 'AI', 'BOTH', 330),
        ('system_email_ingest', 'Email Ingestion (IMAP)', 'Inbound email ingestion UI and tasks.', 'SYSTEM', 'SYSTEM', 400),
        ('system_job_auto_close', 'Job Auto-Close', 'Automated stale job closing.', 'SYSTEM', 'SYSTEM', 410),
        ('system_data_enrichment', 'Data Enrichment', 'Data pipeline and enrichment dashboard.', 'SYSTEM', 'SYSTEM', 420),
        ('system_exec_reports', 'Executive Reports', 'Executive / war-room style reports.', 'SYSTEM', 'SYSTEM', 430),
    ]

    for key, label, description, category, applies_to, sort_order in rows:
        FeatureFlag.objects.update_or_create(
            key=key,
            defaults={
                'label': label,
                'description': description,
                'category': category,
                'applies_to': applies_to,
                'sort_order': sort_order,
                'is_enabled': True,
                'enabled_for_consultants': True,
                'enabled_for_employees': True,
            },
        )

    def _ids(*keys):
        return list(FeatureFlag.objects.filter(key__in=keys).values_list('id', flat=True))

    recruiter_keys = [
        'employee_workflow', 'employee_csv_export', 'consultant_messaging',
        'ai_resume_generation', 'ai_cover_letter', 'ai_rejection_analysis', 'ai_interview_prep',
    ]
    senior_keys = recruiter_keys + [
        'employee_job_pool', 'employee_bulk_ops', 'employee_analytics', 'employee_company_enrich',
        'consultant_messaging',
    ]
    manager_keys = [
        'employee_job_pool', 'employee_bulk_ops', 'employee_analytics', 'employee_company_enrich',
        'employee_workflow', 'employee_csv_export', 'employee_impersonate', 'employee_lock_override',
        'consultant_messaging',
        'ai_resume_generation', 'ai_cover_letter', 'ai_rejection_analysis', 'ai_interview_prep',
        'system_email_ingest', 'system_job_auto_close', 'system_data_enrichment', 'system_exec_reports',
    ]

    specs = [
        ('recruiter', 'Recruiter', 1, 'blue', recruiter_keys),
        ('senior_recruiter', 'Senior Recruiter', 2, 'indigo', senior_keys),
        ('manager', 'Manager', 3, 'purple', manager_keys),
    ]

    for slug, name, level, color, keys in specs:
        des, _ = EmployeeDesignation.objects.update_or_create(
            slug=slug,
            defaults={'name': name, 'level': level, 'color': color, 'is_active': True},
        )
        des.allowed_features.set(_ids(*keys))


def unseed_feature_flags(apps, schema_editor):
    EmployeeDesignation = apps.get_model('core', 'EmployeeDesignation')
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    EmployeeDesignation.objects.all().delete()
    FeatureFlag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_platformconfig_job_pool_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('CONSULTANT', 'Consultant'), ('EMPLOYEE', 'Employee'), ('AI', 'AI / LLM'), ('SYSTEM', 'System')], default='CONSULTANT', max_length=20)),
                ('applies_to', models.CharField(choices=[('CONSULTANT', 'Consultants'), ('EMPLOYEE', 'Employees'), ('BOTH', 'Both'), ('SYSTEM', 'System only')], default='CONSULTANT', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master kill switch for this flag.')),
                ('enabled_for_consultants', models.BooleanField(default=True)),
                ('enabled_for_employees', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_flags_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature flag',
                'verbose_name_plural': 'Feature flags',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('color', models.CharField(blank=True, default='gray', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_features', models.ManyToManyField(blank=True, related_name='designations', to='core.featureflag')),
            ],
            options={
                'ordering': ['level', 'name'],
            },
        ),
        migrations.RunPython(seed_feature_flags_and_designations, unseed_feature_flags),
    ]
