# Generated by Django 5.2.13 on 2026-06-07 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auditlog_advanced_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('ERROR', 'Error (500)'), ('WARNING', 'Warning (4xx)'), ('SLOW', 'Slow Request')], default='ERROR', max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(default='GET', max_length=10)),
                ('status_code', models.PositiveIntegerField(default=500)),
                ('error_type', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_time_ms', models.PositiveIntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='core_errorl_severit_37ec1d_idx'), models.Index(fields=['path', '-created_at'], name='core_errorl_path_ccdd91_idx'), models.Index(fields=['resolved', '-created_at'], name='core_errorl_resolve_8c38af_idx')],
            },
        ),
    ]
