# Generated by Django 5.2.13 on 2026-06-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_llmconfig_multiprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconfig',
            name='color_theme',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('violet', 'Violet'), ('blue', 'Blue'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('rose', 'Rose'), ('amber', 'Amber'), ('slate', 'Slate'), ('saffron', 'Saffron'), ('chakra', 'Chakra'), ('banyan', 'Banyan')], default='indigo', help_text='Primary brand color used across the entire platform.', max_length=20),
        ),
    ]
