# Generated by Django 5.2.13 on 2026-06-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_platformconfig_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_allow_push_with_warnings',
            field=models.BooleanField(default=True, help_text='Allow reviewers to push approved RawJobs into vetting even when verifier warnings still exist. Every override is audited.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_backfill_batch_size',
            field=models.PositiveIntegerField(default=200, help_text='Default batch size for historical RawJob dual-classification backfills. Used by the review queue and admin-triggered backfill runs.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_require_approval_for_sync',
            field=models.BooleanField(default=False, help_text='When enabled, RawJobs with real JD text must have an approved dual-classification result before they can sync into the vetting queue.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_secondary_provider_default',
            field=models.CharField(blank=True, default='', help_text="Optional default secondary provider label for review tooling, for example 'codex' or 'claude'.", max_length=20),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_shadow_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, RawJobs with usable JD text automatically queue the shadow dual-classification workflow in the background.'),
        ),
    ]
