# Generated by Django 5.2.13 on 2026-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_platformconfig_dual_classification_allow_push_with_warnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_secondary_prompt_version',
            field=models.CharField(blank=True, default='runtime_v1', help_text='Prompt version tag stored on automatic secondary classifier runs. Useful for audits and controlled prompt upgrades.', max_length=40),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='dual_classification_secondary_runtime_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, the shadow dual-classification task will call the configured secondary provider through the central LLM runtime instead of waiting for manual JSON paste.'),
        ),
    ]
