# Generated by Codex on 2026-06-17

from django.db import migrations


def seed_classification_workspace_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("core", "FeatureFlag")

    rows = [
        (
            "employee_classification_workspace_v2",
            "Classification Workspace V2",
            "Enables the dedicated classification workspace pages during the safe restructure rollout.",
            "EMPLOYEE",
            "EMPLOYEE",
            271,
            False,
        ),
        (
            "employee_classification_settings_v2",
            "Classification Settings V2",
            "Enables the dedicated classification settings surface instead of embedding those controls in broad platform settings.",
            "EMPLOYEE",
            "EMPLOYEE",
            272,
            False,
        ),
        (
            "employee_classification_metrics_v2",
            "Classification Metrics V2",
            "Enables the dedicated classification metrics and throughput views.",
            "EMPLOYEE",
            "EMPLOYEE",
            273,
            False,
        ),
        (
            "employee_legacy_rawjob_review_bridge",
            "Legacy RawJob Review Bridge",
            "Keeps legacy RawJob review entry points available while the new classification workspace reaches parity.",
            "EMPLOYEE",
            "EMPLOYEE",
            274,
            True,
        ),
    ]

    for key, label, description, category, applies_to, sort_order, enabled in rows:
        FeatureFlag.objects.update_or_create(
            key=key,
            defaults={
                "label": label,
                "description": description,
                "category": category,
                "applies_to": applies_to,
                "sort_order": sort_order,
                "is_enabled": enabled,
                "enabled_for_consultants": False,
                "enabled_for_employees": True,
                "icon": "workflow",
            },
        )


def unseed_classification_workspace_flags(apps, schema_editor):
    FeatureFlag = apps.get_model("core", "FeatureFlag")
    FeatureFlag.objects.filter(
        key__in=[
            "employee_classification_workspace_v2",
            "employee_classification_settings_v2",
            "employee_classification_metrics_v2",
            "employee_legacy_rawjob_review_bridge",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_platformconfig_dual_classification_secondary_prompt_version_and_more"),
    ]

    operations = [
        migrations.RunPython(
            seed_classification_workspace_flags,
            unseed_classification_workspace_flags,
        ),
    ]
