# Generated by Django 5.2.13 on 2026-06-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_seed_classification_workspace_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='routing_backfill_batch_size',
            field=models.PositiveIntegerField(default=1000, help_text='Default batch size for active-job routing refresh actions.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_enforce_clearance',
            field=models.BooleanField(default=True, help_text='Block consultant/job matches when the job requires clearance and the consultant is not eligible.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_enforce_country_match',
            field=models.BooleanField(default=True, help_text='Apply consultant country preferences during routing eligibility checks.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_enforce_employment_preferences',
            field=models.BooleanField(default=True, help_text='Apply consultant employment preference filters like W2/C2C/1099 during routing eligibility checks.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_enforce_seniority_match',
            field=models.BooleanField(default=True, help_text='Apply consultant seniority preferences during routing eligibility checks.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_enforce_work_authorization',
            field=models.BooleanField(default=True, help_text='Block consultant/job matches when visa or work authorization rules conflict.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_enforce_work_mode',
            field=models.BooleanField(default=False, help_text='Apply consultant work mode preferences such as remote, hybrid, or onsite.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_ready_confidence_threshold',
            field=models.FloatField(default=0.55, help_text='Jobs at or above this routing confidence can auto-enter READY status when required signals are present.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_country',
            field=models.BooleanField(default=False, help_text='Require at least one routed country before a job can auto-enter READY status.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_seniority',
            field=models.BooleanField(default=False, help_text='Require routed seniority before a job can auto-enter READY status.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_work_authorization',
            field=models.BooleanField(default=False, help_text='Require structured work authorization evidence before a job can auto-enter READY status.'),
        ),
    ]
