# Generated by Django 5.2.13 on 2026-06-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_platformconfig_routing_backfill_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_parsed_jd_for_live',
            field=models.BooleanField(default=True, help_text='Require a successful parsed JD before a pooled job can be approved live.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_parsed_jd_for_pool',
            field=models.BooleanField(default=False, help_text='Require a successful parsed JD before a harvested job can enter the vetting pool.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_ready_for_live',
            field=models.BooleanField(default=True, help_text='Require routing READY or OVERRIDDEN status before a pooled job can be approved live.'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='routing_require_ready_for_pool',
            field=models.BooleanField(default=False, help_text='Require routing READY status before a harvested job can enter the vetting pool.'),
        ),
    ]
