# Generated by Django 5.2.13 on 2026-06-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_platformconfig_routing_require_parsed_jd_for_live_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(blank=True, default='CHENN Hiring Cloud', max_length=120)),
                ('hero_title', models.CharField(default='The operating layer for hiring execution.', max_length=180)),
                ('hero_body', models.TextField(default='Run intake, JD classification, vetting, consultant matching, and submissions from one system built for recruiting operations.')),
                ('hero_primary_label', models.CharField(blank=True, default='Explore careers', max_length=60)),
                ('hero_primary_url', models.CharField(blank=True, default='/careers/', max_length=255)),
                ('hero_secondary_label', models.CharField(blank=True, default='Request employer access', max_length=60)),
                ('hero_secondary_url', models.CharField(blank=True, default='/employees/request-access/', max_length=255)),
                ('proof_stat_1_value', models.CharField(default='Intake', max_length=40)),
                ('proof_stat_1_label', models.CharField(default='Raw jobs, source health, and routing controls', max_length=120)),
                ('proof_stat_2_value', models.CharField(default='Classify', max_length=40)),
                ('proof_stat_2_label', models.CharField(default='Structured JD extraction and review gates', max_length=120)),
                ('proof_stat_3_value', models.CharField(default='Close', max_length=40)),
                ('proof_stat_3_label', models.CharField(default='Consultant matching, marketing, and submission workflow', max_length=120)),
                ('workflow_title', models.CharField(default='How CHENN runs hiring', max_length=120)),
                ('workflow_body', models.TextField(default='Use one operating model from intake through placement instead of stitching together job boards, spreadsheets, and manual review.')),
                ('workflow_step_1_title', models.CharField(default='Intake', max_length=80)),
                ('workflow_step_1_body', models.TextField(default='Capture raw jobs, normalize source signals, and protect queue quality.')),
                ('workflow_step_2_title', models.CharField(default='Classify', max_length=80)),
                ('workflow_step_2_body', models.TextField(default='Extract role family, country, seniority, and work-authorization signals from the JD.')),
                ('workflow_step_3_title', models.CharField(default='Match', max_length=80)),
                ('workflow_step_3_body', models.TextField(default='Route vetted jobs to the right consultant pool with structured controls.')),
                ('workflow_step_4_title', models.CharField(default='Market', max_length=80)),
                ('workflow_step_4_body', models.TextField(default='Move ready jobs into live workflows for resume generation, submissions, and tracking.')),
                ('consultant_title', models.CharField(default='Consultant onboarding', max_length=120)),
                ('consultant_body', models.TextField(default='Submit your profile once, keep your routing preferences current, and receive jobs that actually fit your market.')),
                ('consultant_cta_label', models.CharField(blank=True, default='Submit consultant profile', max_length=60)),
                ('employer_title', models.CharField(default='Employer access', max_length=120)),
                ('employer_body', models.TextField(default='Give hiring teams one place to review incoming roles, control quality, and manage submission operations.')),
                ('employer_cta_label', models.CharField(blank=True, default='Request access', max_length=60)),
                ('careers_title', models.CharField(default='Open roles at CHENN clients', max_length=120)),
                ('careers_body', models.TextField(default='Browse live openings, inspect the real JD, and move into consultant workflows without losing context.')),
                ('signin_title', models.CharField(default='Access the right CHENN workspace', max_length=120)),
                ('signin_body', models.TextField(default='Use the same credentials, but start from the portal that matches your role: admin, employee, or consultant.')),
                ('consultant_onboarding_title', models.CharField(default='Set your consultant routing profile', max_length=120)),
                ('consultant_onboarding_body', models.TextField(default='Complete skills, geography, work authorization, and availability so the platform can route better-fit jobs automatically.')),
                ('employee_onboarding_title', models.CharField(default='Set your employee workspace', max_length=120)),
                ('employee_onboarding_body', models.TextField(default='Confirm department, role, and hiring context so the dashboard and job workflow open in the right mode.')),
            ],
        ),
    ]
