# Generated by Django 5.2.13 on 2026-06-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_publicsitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (follow device)')], default='light', help_text="Default light/dark appearance. Visitors can still toggle it; 'Auto' follows the device's system preference.", max_length=10),
        ),
    ]
