# Generated by Django 5.2.13 on 2026-04-14 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0009_add_company_type'),
        ('jobs', '0013_job_validation_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoardPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('url_patterns', models.JSONField(default=list, help_text="List of URL substrings to match (e.g. ['myworkdayjobs.com']).")),
                ('api_type', models.CharField(choices=[('workday_api', 'Workday REST API'), ('greenhouse_api', 'Greenhouse REST API'), ('lever_api', 'Lever REST API'), ('ashby_graphql', 'Ashby GraphQL'), ('html_scrape', 'HTML Scrape'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('fetch_endpoint_tmpl', models.TextField(blank=True, help_text='URL template. Use {tenant} as placeholder.')),
                ('headers_json', models.JSONField(blank=True, default=dict, help_text='Default request headers.')),
                ('rate_limit_per_min', models.PositiveSmallIntegerField(default=10)),
                ('requires_auth', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('color_hex', models.CharField(blank=True, default='#6B7280', help_text='Badge colour hex e.g. #4A90D9', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('last_harvested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Board Platform',
                'verbose_name_plural': 'Job Board Platforms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('MANUAL', 'Manual (Superuser)')], default='SCHEDULED', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('companies_targeted', models.PositiveIntegerField(default=0)),
                ('jobs_fetched', models.PositiveIntegerField(default=0)),
                ('jobs_new', models.PositiveIntegerField(default=0)),
                ('jobs_duplicate', models.PositiveIntegerField(default=0)),
                ('jobs_failed', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('triggered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_harvest_runs', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_runs', to='harvest.jobboardplatform')),
            ],
            options={
                'verbose_name': 'Harvest Run',
                'verbose_name_plural': 'Harvest Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPlatformLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_career_url', models.URLField(blank=True, help_text='Custom/own career page if no standard ATS.')),
                ('tenant_id', models.CharField(blank=True, help_text='ATS tenant / token extracted from career URL.', max_length=255)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('detection_method', models.CharField(choices=[('URL_PATTERN', 'URL Pattern Match'), ('HTTP_HEAD', 'HTTP Redirect Follow'), ('HTML_PARSE', 'HTML Content Parse'), ('MANUAL', 'Manually Set'), ('UNDETECTED', 'Could Not Detect')], default='UNDETECTED', max_length=15)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by superuser.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_label', to='companies.company')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_platform_labels', to=settings.AUTH_USER_MODEL)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='harvest.jobboardplatform')),
            ],
            options={
                'verbose_name': 'Company Platform Label',
                'verbose_name_plural': 'Company Platform Labels',
                'ordering': ['company__name'],
            },
        ),
        migrations.CreateModel(
            name='HarvestedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=500)),
                ('url_hash', models.CharField(db_index=True, max_length=64)),
                ('original_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=300)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-Time'), ('PART_TIME', 'Part-Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=10)),
                ('salary_raw', models.CharField(blank=True, max_length=200)),
                ('description_html', models.TextField(blank=True)),
                ('description_text', models.TextField(blank=True)),
                ('requirements_text', models.TextField(blank=True)),
                ('benefits_text', models.TextField(blank=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('closes_date', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SYNCED', 'Synced to Pool'), ('SKIPPED', 'Skipped (Duplicate)'), ('FAILED', 'Sync Failed')], default='PENDING', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_jobs', to='companies.company')),
                ('synced_to_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_source', to='jobs.job')),
                ('harvest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_jobs', to='harvest.harvestrun')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvested_jobs', to='harvest.jobboardplatform')),
            ],
            options={
                'verbose_name': 'Harvested Job',
                'verbose_name_plural': 'Harvested Jobs',
                'ordering': ['-fetched_at'],
                'unique_together': {('platform', 'url_hash')},
            },
        ),
    ]
