# Generated by Django 5.2.13 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0012_rawjob_enrichment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawjob',
            name='jd_backfill_locked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
