# Generated by Django 5.2.13 on 2026-04-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0013_rawjob_jd_backfill_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSPlatformPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backfill', models.BooleanField(default=True, help_text='Queue JD backfill after fetch when listings need detail fetch (e.g. title-only).')),
                ('backfill_priority', models.SmallIntegerField(default=0, help_text='Higher = scheduled sooner when backfill workers are contended.')),
                ('fetch_cadence_hours', models.PositiveSmallIntegerField(blank=True, help_text='Minimum hours between scheduled full fetches; null = use global/celery schedule default.', null=True)),
                ('min_quality_score', models.FloatField(blank=True, help_text='Optional floor 0.0–1.0; jobs below target quality may be archived (future pipeline gate).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_policy', to='harvest.jobboardplatform')),
            ],
            options={
                'verbose_name': 'ATS platform policy',
                'verbose_name_plural': 'ATS platform policies',
            },
        ),
    ]
