# Generated by Django 5.2.13 on 2026-04-21 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0014_ats_platform_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backfill', models.BooleanField(default=False, help_text='If true, fetch auto-queues JD backfill for new jobs on this platform.')),
                ('backfill_priority', models.PositiveSmallIntegerField(default=5, help_text='1 = highest, 10 = lowest. Backfill workers dequeue lowest number first.')),
                ('fetch_cadence_hours', models.PositiveIntegerField(default=24, help_text='Minimum hours between per-company fetches on this platform.')),
                ('inter_request_delay_ms', models.PositiveIntegerField(default=1500, help_text='Delay between consecutive requests (APIs ~1500, scrapers ~5000).')),
                ('min_quality_score', models.FloatField(default=0.3, help_text='Jobs below this score are auto-archived after enrichment.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='harvest.jobboardplatform')),
            ],
            options={
                'verbose_name': 'Platform Config',
                'ordering': ['platform__name'],
            },
        ),
        migrations.DeleteModel(
            name='ATSPlatformPolicy',
        ),
    ]
