# Generated by Django 5.2.13 on 2026-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0065_opsrun_retry_failed_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestengineconfig',
            name='remote_unknown_policy',
            field=models.CharField(choices=[('review', 'Send to review'), ('target', 'Treat as priority target'), ('cold', 'Mark cold')], default='review', help_text="What to do with remote jobs that signal remote but have no resolvable country. 'review' keeps current behavior; 'target' accepts them (most remote roles are reachable); 'cold' drops them.", max_length=8, verbose_name='Remote (no country) policy'),
        ),
    ]
