# Generated by Django 5.2.13 on 2026-06-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0066_remote_unknown_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestengineconfig',
            name='remote_llm_jd_scan',
            field=models.BooleanField(default=False, help_text='For remote jobs with no resolvable country, ask the LLM to read the job description and extract a work location before applying the remote policy. Costs one LLM call per such job — use with the central LLM config.', verbose_name='LLM scan JD for remote location'),
        ),
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='remote_unknown_policy',
            field=models.CharField(choices=[('review', 'Send to review'), ('us', 'Default to USA'), ('target', 'Treat as priority target'), ('cold', 'Mark cold')], default='review', help_text="What to do with a remote job after location + JD scanning still finds no country. 'review' keeps it in the queue; 'us' assumes USA (most remote roles); 'target' accepts as priority; 'cold' drops it.", max_length=8, verbose_name='Remote (no country) policy'),
        ),
    ]
