# Generated by Django 5.2.13 on 2026-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0068_alter_harvestopsrun_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestengineconfig',
            name='pre_storage_strict_strong_only',
            field=models.BooleanField(default=False, help_text='When True (and pre-storage filter enabled, enforcement mode), ONLY titles that match a category phrase (STRONG) are stored. POSSIBLE (tech-adjacent but no exact phrase) and non-ASCII UNKNOWN titles are also dropped before any DB write — not just HARD_NO. Blank titles are kept as a fail-safe canary. This is title-only: it does NOT touch location/scope, so the unknown-country Location Review queue is unaffected. Verify in audit mode first.', verbose_name='Pre-storage strict mode (STRONG matches only)'),
        ),
    ]
