# Generated by Django 5.2.13 on 2026-07-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0070_enable_strict_strong_only_for_live_selective_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestengineconfig',
            name='obscura_binary_path',
            field=models.CharField(default='obscura', help_text='Executable path inside the worker container. Default assumes the binary is on PATH.', max_length=255, verbose_name='Obscura binary path'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='obscura_enabled',
            field=models.BooleanField(default=False, help_text='Allow the HTML fallback harvester to use the Obscura headless renderer for SPA-heavy boards when a platform runtime rule opts into it.', verbose_name='Enable Obscura renderer'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='obscura_stealth',
            field=models.BooleanField(default=False, help_text='Enable Obscura anti-detection mode for boards that block plain automation.', verbose_name='Obscura stealth mode'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='obscura_timeout_secs',
            field=models.PositiveSmallIntegerField(default=20, help_text='Hard timeout per rendered page fetch.', verbose_name='Obscura timeout (seconds)'),
        ),
        migrations.AddField(
            model_name='harvestengineconfig',
            name='obscura_wait_until',
            field=models.CharField(choices=[('load', 'load'), ('domcontentloaded', 'domcontentloaded'), ('networkidle0', 'networkidle0')], default='networkidle0', help_text='Browser lifecycle event to wait for before dumping rendered HTML.', max_length=24, verbose_name='Obscura wait condition'),
        ),
        migrations.AddField(
            model_name='platformengineconfig',
            name='html_render_backend',
            field=models.CharField(choices=[('requests', 'Native requests'), ('obscura_auto', 'Obscura with native fallback'), ('obscura_only', 'Obscura only')], default='requests', help_text='Renderer for generic HTML board fetching. Use Obscura only for SPA-heavy boards that requests-based HTML misses.', max_length=24),
        ),
    ]
