# Generated by Django 5.2.13 on 2026-07-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0072_enforce_strong_only_intake_and_vetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetgateconfig',
            name='allow_possible_filter',
            field=models.BooleanField(default=False, help_text='Deprecated. Vetting is locked to STRONG-only intake policy.', verbose_name='Allow POSSIBLE filter decision'),
        ),
    ]
