# Generated by Django 5.2.13 on 2026-07-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0073_alter_vetgateconfig_allow_possible_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetgateconfig',
            name='allow_possible_filter',
        ),
        migrations.RemoveField(
            model_name='vetgateconfig',
            name='blocked_domains',
        ),
    ]
