# Generated by Django 5.2.13 on 2026-07-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0075_deadlinkreviewitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestengineconfig',
            name='cleanup_inactive_age_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Inactive rows older than this are purged by Phase 3 of cleanup. Default 7 days. Rows that are inactive+PENDING are purged after the safe buffer (Phase 2) when they never touched the pipeline. Synced, pool-linked, or admin-review rows are kept until approved purge.', verbose_name='Cleanup — inactive row max age (days)'),
        ),
    ]
