# Generated by Django 5.2.11 on 2026-02-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0012_resumedraft_generation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplatepack',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='resumetemplatepack',
            name='marketing_roles',
        ),
        migrations.DeleteModel(
            name='ResumeTemplate',
        ),
        migrations.DeleteModel(
            name='ResumeTemplatePack',
        ),
    ]
