# Generated by Django 5.2.11 on 2026-04-04 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_phase4_5'),
        ('resumes', '0013_remove_resumetemplatepack_templates_and_more'),
        ('users', '0018_phase3_pipeline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='Generated cover letter text')),
                ('version', models.PositiveIntegerField(default=1)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='users.consultantprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cover_letters', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('consultant', 'job', 'version')},
            },
        ),
    ]
