# Generated by Django 5.2.11 on 2026-04-04 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0014_phase4_5'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Version label, e.g. 'v2.1 — ATS focus'", max_length=200)),
                ('system_prompt', models.TextField(help_text='The SYSTEM role text sent to the LLM (defines who it is and the rules).')),
                ('generation_rules', models.TextField(blank=True, help_text='Additional generation rules appended after the candidate + JD inputs. Use this for output format, section rules, edge cases, quality gates.')),
                ('is_active', models.BooleanField(default=False, help_text='Only one prompt can be active. Activating this deactivates others.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
