# Generated by Django 5.2.11 on 2026-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0015_master_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprompt',
            name='default_input_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Default toggles for which consultant data blocks are included in the candidate profile sent to the LLM (per prompt version). Keys: personal, experience, education, certifications, skills, total_years, base_resume.'),
        ),
    ]
