# Generated by Django 5.2.11 on 2026-04-06 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0016_master_prompt_default_input_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_builtin', models.BooleanField(default=False)),
                ('font_family', models.CharField(choices=[('Georgia, serif', 'Georgia (Serif)'), ('"Times New Roman", serif', 'Times New Roman'), ('Garamond, Georgia, serif', 'Garamond'), ('"Palatino Linotype", serif', 'Palatino'), ('Arial, sans-serif', 'Arial'), ('"Helvetica Neue", Arial, sans-serif', 'Helvetica Neue'), ('Calibri, Arial, sans-serif', 'Calibri'), ('"Trebuchet MS", sans-serif', 'Trebuchet MS'), ('"Open Sans", sans-serif', 'Open Sans')], default='Georgia, serif', max_length=120)),
                ('name_size', models.PositiveSmallIntegerField(default=22)),
                ('header_size', models.PositiveSmallIntegerField(default=13)),
                ('body_size', models.PositiveSmallIntegerField(default=11)),
                ('contact_size', models.PositiveSmallIntegerField(default=10)),
                ('accent_color', models.CharField(default='#1e3a5f', max_length=7)),
                ('name_color', models.CharField(default='#111827', max_length=7)),
                ('body_color', models.CharField(default='#374151', max_length=7)),
                ('margin_top', models.FloatField(default=0.75)),
                ('margin_bottom', models.FloatField(default=0.75)),
                ('margin_left', models.FloatField(default=0.75)),
                ('margin_right', models.FloatField(default=0.75)),
                ('line_height', models.FloatField(default=1.3)),
                ('para_spacing', models.PositiveSmallIntegerField(default=5, help_text='pt between paragraphs')),
                ('section_spacing', models.PositiveSmallIntegerField(default=10, help_text='pt above section headers')),
                ('header_style', models.CharField(choices=[('underline', 'Underline'), ('bar', 'Filled Bar'), ('caps', 'All-Caps + Thin Rule'), ('plain', 'Plain (ATS Safe)')], default='underline', max_length=20)),
                ('show_dividers', models.BooleanField(default=True)),
                ('bullet_char', models.CharField(default='•', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_builtin', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEditorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_json', models.JSONField(blank=True, default=dict, help_text='Parsed sections: name, contact, summary, skills[], experience[], education[], certifications[]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_state', to='resumes.resumedraft')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editor_states', to='resumes.resumetemplate')),
            ],
        ),
    ]
