# Generated by Django 5.2.13 on 2026-06-06 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_job_auto_marketing_role_slugs'),
        ('resumes', '0018_add_auto_generated_to_resumedraft'),
        ('users', '0028_deactivate_marketing_role_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('jd_intelligence', models.JSONField(blank=True, default=dict)),
                ('matching_matrix', models.JSONField(blank=True, default=dict)),
                ('section_results', models.JSONField(blank=True, default=dict, help_text='Per-section: {section: {content, tokens, latency_ms, retries}}')),
                ('quality_gate', models.JSONField(blank=True, default=dict, help_text='{ats_score, validation_errors, retried_sections, passed}')),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_llm_calls', models.PositiveIntegerField(default=0)),
                ('total_latency_ms', models.PositiveIntegerField(default=0)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.consultantprofile')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='resumes.resumedraft')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('summary', 'Professional Summary'), ('skills', 'Skills'), ('experience', 'Professional Experience'), ('education', 'Education & Certifications')], max_length=20)),
                ('system_prompt', models.TextField(blank=True, help_text='Section-specific system prompt. If blank, falls back to MasterPrompt.system_prompt.')),
                ('generation_rules', models.TextField(blank=True, help_text='Section-specific rules appended to the user prompt for this section.')),
                ('temperature_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override temperature for this section. Null = use LLMConfig default.', max_digits=3, null=True)),
                ('max_tokens_override', models.PositiveIntegerField(blank=True, help_text='Override max tokens for this section. Null = auto-calculated.', null=True)),
                ('master_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_prompts', to='resumes.masterprompt')),
            ],
            options={
                'ordering': ['section_type'],
                'unique_together': {('master_prompt', 'section_type')},
            },
        ),
    ]
