# Generated by Django 5.2.13 on 2026-06-15 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0025_resumedraft_review_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JDExtractorPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Version label, e.g. 'v2 — stricter evidence'", max_length=200)),
                ('prompt_text', models.TextField(help_text='The full system prompt sent to the JD extractor LLM.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
