# Generated by Django 5.2.13 on 2026-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0026_jd_extractor_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedraft',
            name='generation_mode',
            field=models.CharField(blank=True, default='', help_text='manual, auto, regenerate, or other workflow mode.', max_length=24),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='generation_reason',
            field=models.CharField(blank=True, default='', help_text='Short machine-readable reason for this draft generation.', max_length=64),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stable fingerprint for reusing an equivalent draft instead of regenerating it.', max_length=96),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='source_classification_source',
            field=models.CharField(blank=True, default='', help_text='backend, secondary, merged, manual, or empty when unavailable.', max_length=24),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='source_primary_role_slug',
            field=models.CharField(blank=True, default='', help_text='Primary marketing role used to target this draft.', max_length=120),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='source_prompt_version',
            field=models.CharField(blank=True, default='', help_text='Extractor/classification prompt version that fed this draft.', max_length=64),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='source_snapshot_approved_at',
            field=models.DateTimeField(blank=True, help_text='When the upstream approved classification was locked in for this draft.', null=True),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='source_snapshot_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Approved classification or job snapshot hash used for this draft.', max_length=64),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='source_snapshot_source',
            field=models.CharField(blank=True, default='', help_text='approved_snapshot or job_record.', max_length=24),
        ),
    ]
