# Generated by Django 5.2.11 on 2026-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_consultantprofile_base_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='match_jd_title_override',
            field=models.BooleanField(blank=True, help_text='Override global setting for matching the most recent role title to the JD title.', null=True),
        ),
    ]
