# Generated by Django 5.2.11 on 2026-03-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='profile_slug',
            field=models.SlugField(blank=True, help_text='Shareable URL slug for public profile, e.g. /c/john-doe', max_length=80, unique=False),
        ),
    ]
