# Generated by Django 5.2.11 on 2026-03-09 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_organisation_model'),
        ('users', '0015_populate_consultant_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation / tenant for white-label mode (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.organisation'),
        ),
    ]
