# Generated by Django 5.2.11 on 2026-04-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_phase3_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailnotificationpreferences',
            name='inapp_interviews',
            field=models.BooleanField(default=True, help_text='In-app alerts for interviews and scheduling.'),
        ),
        migrations.AddField(
            model_name='useremailnotificationpreferences',
            name='inapp_jobs',
            field=models.BooleanField(default=True, help_text='In-app alerts for job postings and job-related notices.'),
        ),
        migrations.AddField(
            model_name='useremailnotificationpreferences',
            name='inapp_submissions',
            field=models.BooleanField(default=True, help_text='In-app alerts for applications and pipeline updates.'),
        ),
        migrations.AddField(
            model_name='useremailnotificationpreferences',
            name='inapp_system',
            field=models.BooleanField(default=True, help_text='In-app alerts for system and account messages.'),
        ),
    ]
