# Generated by Django 5.2.11 on 2026-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_notification_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='preferred_location',
            field=models.CharField(blank=True, default='', help_text="City, State used in resume header. e.g. 'Jersey City, NJ' or 'Remote'", max_length=120),
        ),
    ]
