# Generated by Django 5.2.13 on 2026-04-14 05:46

import django.db.models.deletion
from django.db import migrations, models


def assign_default_designation(apps, schema_editor):
    EmployeeProfile = apps.get_model('users', 'EmployeeProfile')
    EmployeeDesignation = apps.get_model('core', 'EmployeeDesignation')
    rec = EmployeeDesignation.objects.filter(slug='recruiter').first()
    if rec:
        EmployeeProfile.objects.filter(designation__isnull=True).update(designation_id=rec.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_feature_flags_and_designations'),
        ('users', '0020_add_preferred_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='RBAC tier — controls which employee feature flags apply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.employeedesignation'),
        ),
        migrations.RunPython(assign_default_designation, noop_reverse),
    ]
