# Generated by Django 5.2.13 on 2026-04-21 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_feature_flags_and_designations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='Embedding float list from text-embedding-3-small')),
                ('model', models.CharField(default='text-embedding-3-small', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='users.consultantprofile')),
            ],
            options={
                'verbose_name': 'Consultant Embedding',
            },
        ),
    ]
