# Generated by Django 5.2.13 on 2026-06-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_deactivate_marketing_role_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='citizenship_countries',
            field=models.JSONField(blank=True, default=list, help_text="Citizenship countries used for routing eligibility, e.g. ['United States']."),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='clearance_eligible',
            field=models.BooleanField(default=False, help_text='Whether the consultant can be routed to jobs requiring security clearance.'),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='employment_preferences',
            field=models.JSONField(blank=True, default=list, help_text="Accepted employment arrangements, e.g. ['w2', 'c2c', '1099', 'full_time']."),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='preferred_work_modes',
            field=models.JSONField(blank=True, default=list, help_text="Accepted work modes, e.g. ['remote', 'hybrid', 'onsite']."),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='requires_visa_sponsorship',
            field=models.BooleanField(blank=True, help_text='Whether the consultant requires visa sponsorship for routed jobs.', null=True),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='visa_status',
            field=models.CharField(blank=True, help_text='Structured visa/work authorization note, e.g. H1B, OPT, Citizen, PR.', max_length=80),
        ),
        migrations.AddField(
            model_name='consultantprofile',
            name='work_authorization_countries',
            field=models.JSONField(blank=True, default=list, help_text='Countries where this consultant can legally work without new sponsorship.'),
        ),
    ]
