# Generated by Django 5.2.13 on 2026-06-22 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_consultantprofile_citizenship_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=160)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('team_size', models.CharField(blank=True, max_length=80)),
                ('hiring_volume', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], db_index=True, default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the employee completes the first-run onboarding flow.', null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='work_location',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.CreateModel(
            name='ConsultantLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('current_title', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='consultant_leads/resumes/')),
                ('resume_text', models.TextField(blank=True)),
                ('preferred_markets', models.CharField(blank=True, help_text='Comma-separated role families or market interests.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('ARCHIVED', 'Archived')], db_index=True, default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_lead_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
