# Generated by Django 5.2.11 on 2026-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('size_band', models.CharField(blank=True, help_text='e.g. startup, SMB, mid-market, enterprise.', max_length=50)),
                ('headcount_range', models.CharField(blank=True, help_text='e.g. 1-10, 11-50, 51-200, 201-1000, 1000+', max_length=50)),
                ('hq_location', models.CharField(blank=True, max_length=255)),
                ('locations', models.TextField(blank=True, help_text='Other office locations (free text).')),
                ('relationship_status', models.CharField(blank=True, help_text='Optional tag like Hot / Warm / Cold / Blacklisted.', max_length=20)),
                ('primary_contact_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('total_interviews', models.PositiveIntegerField(default=0)),
                ('total_offers', models.PositiveIntegerField(default=0)),
                ('total_placements', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
