# Generated by Django 5.2.11 on 2026-03-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    def backfill_companies(apps, schema_editor):
        Job = apps.get_model('jobs', 'Job')
        Company = apps.get_model('companies', 'Company')

        existing = {}
        for job in Job.objects.all():
            name = (job.company or "").strip()
            if not name:
                continue
            key = name.lower()
            if key in existing:
                company = existing[key]
            else:
                company, _ = Company.objects.get_or_create(name=name)
                existing[key] = company
            if not job.company_obj_id:
                job.company_obj = company
                job.save(update_fields=['company_obj'])

    operations = [
        migrations.RunPython(backfill_companies, migrations.RunPython.noop),
    ]
