# Generated by Django 5.2.11 on 2026-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_backfill_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='website_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
