# Generated by Django 5.2.11 on 2026-03-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_url_validation_fields'),
        ('users', '0016_user_organisation_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='blacklist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_blacklisted',
            field=models.BooleanField(default=False, help_text='When true, new submissions to this company should be blocked.'),
        ),
        migrations.CreateModel(
            name='CompanyDoNotSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateField(blank=True, help_text='Optional end date. Blank = indefinite.', null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dnd_rules', to='companies.company')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_dnd_rules', to='users.consultantprofile')),
            ],
            options={
                'unique_together': {('company', 'consultant')},
            },
        ),
    ]
