# Generated by Django for Phase 3 enrichment

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_company_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, help_text="Short company description (from OG/website)."),
        ),
        migrations.AddField(
            model_name="company",
            name="enrichment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("enriched", "Enriched"),
                    ("failed", "Failed"),
                    ("stale", "Stale"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="enriched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="enrichment_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="data_quality_score",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0-100, how complete this record is.",
            ),
        ),
    ]
