# Generated by Django 5.2.11 on 2026-03-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fields_updated', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_logs', to='companies.company')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
