# Generated by Django 5.2.11 on 2026-04-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_enrichment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('product', 'Product Company'), ('service', 'Service-Based'), ('consultancy', 'Consultancy'), ('staffing', 'Staffing / Body Shop'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Product / Service-Based / Consultancy / Staffing — auto-detected by enrichment.', max_length=20),
        ),
    ]
