# Generated by Django 5.2.13 on 2026-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_companysavedview'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysavedview',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
