# Generated by Django 5.2.13 on 2026-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_companysavedview_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysavedview',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysavedview',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='companysavedview',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
