# Generated by Django 5.2.13 on 2026-04-21 08:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0014_phase2_3_embeddings_analytics'),
        ('submissions', '0014_add_source_to_submission'),
        ('users', '0022_phase2_3_embeddings_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('jobs_harvested_total', models.PositiveIntegerField(default=0)),
                ('jobs_in_pool', models.PositiveIntegerField(default=0)),
                ('jobs_live', models.PositiveIntegerField(default=0)),
                ('jobs_closed_today', models.PositiveIntegerField(default=0)),
                ('submissions_total', models.PositiveIntegerField(default=0)),
                ('submissions_applied', models.PositiveIntegerField(default=0)),
                ('submissions_interview', models.PositiveIntegerField(default=0)),
                ('submissions_offer', models.PositiveIntegerField(default=0)),
                ('submissions_placed', models.PositiveIntegerField(default=0)),
                ('submissions_rejected', models.PositiveIntegerField(default=0)),
                ('active_placements', models.PositiveIntegerField(default=0)),
                ('revenue_mtd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_bill_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_pay_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consultants_active', models.PositiveIntegerField(default=0)),
                ('consultants_bench', models.PositiveIntegerField(default=0)),
                ('consultants_placed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Snapshot',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('RESUME_GENERATED', 'Resume Generated'), ('SUBMITTED', 'Submitted'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('PLACED', 'Placed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], max_length=30)),
                ('source', models.CharField(blank=True, help_text='e.g. email_parser, manual, auto_approve', max_length=50)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events_acted', to=settings.AUTH_USER_MODEL)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='users.consultantprofile')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='jobs.job')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='submissions.applicationsubmission')),
            ],
            options={
                'verbose_name': 'Funnel Event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['stage', 'occurred_at'], name='analytics_f_stage_3ab322_idx'), models.Index(fields=['consultant', 'stage'], name='analytics_f_consult_f0dac1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RevenueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('hours_billed', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bill_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_records', to='submissions.placement')),
            ],
            options={
                'verbose_name': 'Revenue Record',
                'ordering': ['-period_start'],
                'unique_together': {('placement', 'period_start')},
            },
        ),
    ]
