from django.urls import path
from . import views
from django.views.generic import RedirectView

from .push_api import ExportLabelsView, PushJobsView, PushStatusView
from .views import (
    CompanyFetchStatusView,
    CompanyLabelListView,
    EngineConfigView,
    VetGateConfigView,
    VetGatePreviewView,
    FetchBatchListView,
    FetchCooldownStatusView,
    FetchBatchDetailView,
    FilterSnapshotDetailView,
    FilterSnapshotListView,
    HarvestBatchActivityView,
    DismissOpsRunView,
    RerunOpsRunView,
    JobDomainListView,
    JobDomainCreateView,
    JobDomainUpdateView,
    JobDomainDeleteView,
    JobDomainApplyDownstreamView,
    JobDomainQuickUpdateView,
    JobDomainImpactApiView,
    JobDomainTestApiView,
    HarvestOpsRunDetailView,
    OpsRunLiveApiView,
    JarvisReScrapeView,
    JarvisApproveView,
    JarvisFetchCompanyJobsView,
    JarvisFetchProgressApiView,
    JarvisFetchProgressView,
    JarvisStatusView,
    JarvisView,
    LabelManualSetView,
    LabelUpdateTenantView,
    LabelVerifyView,
    PlatformCreateView,
    PlatformDeleteView,
    PlatformListView,
    PlatformToggleView,
    PlatformUpdateView,
    RawJobCompanyBreakdownView,
    RawJobCheckLiveStatusView,
    RawJobDetailView,
    RawJobListView,
    RawJobResumeProfileView,
    RawJobStatsView,
    BoardAnalyticsDashboardView,
    BoardAnalyticsView,
    BoardDrillDownView,
    RawJobWorkflowInsightsView,
    SelectiveRoleCategoryCreateView,
    SelectiveRoleCategoryListView,
    SelectiveRoleCategoryUpdateView,
    SelectiveTitleTestApiView,
    SkippedTitleRecoverView,
    SkippedTitlesAuditView,
    RunBackfillDescriptionsView,
    RunBackfillResumeContractView,
    RunBackfillNowView,
    RunBulkSyncView,
    RunValidateRawUrlsView,
    RunRetryFailedFetchesView,
    RunSyncSelectedRawJobsView,
    RunCleanupNowView,
    RunDetectNowView,
    RunEnrichExistingView,
    RunHarvestNowView,
    RunSyncNowView,
    RunVerifyPortalsView,
    ScheduleConfigView,
    SetupScheduleView,
    StopBatchView,
    ResumeBatchView,
    TriggerBatchFetchView,
    TriggerCompanyFetchView,
    DuplicateListView,
    DuplicateRunView,
    DuplicateResolveView,
    DuplicateBulkResolveView,
    UnknownCountryReviewView,
    ZeroTechCompaniesView,
)

urlpatterns = [
    # Platform Registry
    path("platforms/", PlatformListView.as_view(), name="harvest-platforms"),
    path("platforms/new/", PlatformCreateView.as_view(), name="harvest-platform-create"),
    path("platforms/<int:pk>/edit/", PlatformUpdateView.as_view(), name="harvest-platform-edit"),
    path("platforms/<int:pk>/delete/", PlatformDeleteView.as_view(), name="harvest-platform-delete"),
    path("platforms/<int:pk>/toggle/", PlatformToggleView.as_view(), name="harvest-platform-toggle"),
    # Schedule
    path("schedule/", ScheduleConfigView.as_view(), name="harvest-schedule"),
    # Monitor (canonicalized to Ops Center)
    path("monitor/", RedirectView.as_view(pattern_name="ops-center", permanent=False), name="harvest-monitor"),
    path("tasks/", RedirectView.as_view(pattern_name="ops-center", permanent=False), name="harvest-tasks"),
    path("tasks/api/", RedirectView.as_view(pattern_name="ops-center-api", permanent=False), name="harvest-tasks-api"),
    # Labels
    path("labels/", CompanyLabelListView.as_view(), name="harvest-labels"),
    path("labels/<int:pk>/verify/", LabelVerifyView.as_view(), name="harvest-label-verify"),
    path("labels/<int:pk>/set-platform/", LabelManualSetView.as_view(), name="harvest-label-set-platform"),
    path("labels/<int:pk>/update-tenant/", LabelUpdateTenantView.as_view(), name="harvest-label-update-tenant"),
    # Raw Jobs — note: static paths before <int:pk>
    path("raw-jobs/", RawJobListView.as_view(), name="harvest-rawjobs"),
    path("raw-jobs/batch-activity/", HarvestBatchActivityView.as_view(), name="harvest-batch-activity"),
    path("raw-jobs/ops-runs/api/live/", OpsRunLiveApiView.as_view(), name="harvest-ops-runs-live-api"),
    path("raw-jobs/ops-runs/<int:pk>/", HarvestOpsRunDetailView.as_view(), name="harvest-ops-run-detail"),
    path("raw-jobs/ops-runs/<int:pk>/dismiss/", DismissOpsRunView.as_view(), name="harvest-ops-run-dismiss"),
    path("raw-jobs/ops-runs/<int:pk>/rerun/", RerunOpsRunView.as_view(), name="harvest-ops-run-rerun"),
    path("raw-jobs/batches/<int:pk>/", FetchBatchDetailView.as_view(), name="harvest-batch-detail"),
    path("raw-jobs/batches/", FetchBatchListView.as_view(), name="harvest-rawjobs-batches"),
    path("raw-jobs/company-status/", CompanyFetchStatusView.as_view(), name="harvest-rawjobs-company-status"),
    path("raw-jobs/stats/", RawJobStatsView.as_view(), name="harvest-rawjobs-stats"),
    path("raw-jobs/insights/", RawJobWorkflowInsightsView.as_view(), name="harvest-rawjobs-insights"),
    path("raw-jobs/api/companies/", RawJobCompanyBreakdownView.as_view(), name="harvest-rawjobs-company-breakdown"),
    path("raw-jobs/<int:pk>/recheck-live/", RawJobCheckLiveStatusView.as_view(), name="harvest-rawjob-recheck-live"),
    path("raw-jobs/<int:pk>/resume-profile/", RawJobResumeProfileView.as_view(), name="harvest-rawjob-resume-profile"),
    path("raw-jobs/<int:pk>/", RawJobDetailView.as_view(), name="harvest-rawjob-detail"),
    # Trigger actions
    path("run/detect/", RunDetectNowView.as_view(), name="harvest-run-detect"),
    path("run/harvest/", RunHarvestNowView.as_view(), name="harvest-run-harvest"),
    path("run/sync/", RunSyncNowView.as_view(), name="harvest-run-sync"),
    path("run/bulk-sync/", RunBulkSyncView.as_view(), name="harvest-run-bulk-sync"),
    path("run/validate-urls/", RunValidateRawUrlsView.as_view(), name="harvest-run-validate-urls"),
    path("run/retry-failed-fetches/", RunRetryFailedFetchesView.as_view(), name="harvest-run-retry-failed-fetches"),
    path("run/sync-selected/", RunSyncSelectedRawJobsView.as_view(), name="harvest-run-sync-selected"),
    path("run/cleanup/", RunCleanupNowView.as_view(), name="harvest-run-cleanup"),
    path("run/backfill/", RunBackfillNowView.as_view(), name="harvest-run-backfill"),
    path("run/verify-portals/", RunVerifyPortalsView.as_view(), name="harvest-run-verify-portals"),
    path("run/fetch-company/", TriggerCompanyFetchView.as_view(), name="harvest-run-fetch-company"),
    path("run/fetch-batch/", TriggerBatchFetchView.as_view(), name="harvest-run-fetch-batch"),
    path("run/stop-batch/", StopBatchView.as_view(), name="harvest-run-stop-batch"),
    path("run/resume-batch/", ResumeBatchView.as_view(), name="harvest-run-resume-batch"),
    path("run/backfill-descriptions/", RunBackfillDescriptionsView.as_view(), name="harvest-run-backfill-descriptions"),
    path("run/enrich-existing/", RunEnrichExistingView.as_view(), name="harvest-run-enrich-existing"),
    path("run/backfill-resume-contract/", RunBackfillResumeContractView.as_view(), name="harvest-run-backfill-resume-contract"),
    path("run/setup-schedule/", SetupScheduleView.as_view(), name="harvest-run-setup-schedule"),
    # API helpers
    path("api/cooldown/", FetchCooldownStatusView.as_view(), name="harvest-api-cooldown"),
    path("board-analytics/", BoardAnalyticsDashboardView.as_view(), name="harvest-board-analytics-dashboard"),
    path("board-analytics/<slug:slug>/", BoardDrillDownView.as_view(), name="harvest-board-drilldown"),
    path("api/board-analytics/", BoardAnalyticsView.as_view(), name="harvest-board-analytics-api"),
    # Local Harvesting Agent — push API (token-authenticated, csrf_exempt)
    path("api/push/labels/", ExportLabelsView.as_view(), name="harvest-push-labels"),
    path("api/push/jobs/", PushJobsView.as_view(), name="harvest-push-jobs"),
    path("api/push/status/", PushStatusView.as_view(), name="harvest-push-status"),
    # Duplicate Engine
    path("raw-jobs/unknown-country/", UnknownCountryReviewView.as_view(), name="harvest-unknown-country-review"),
    path("duplicates/", DuplicateListView.as_view(), name="harvest-duplicates"),
    path("duplicates/run/", DuplicateRunView.as_view(), name="harvest-duplicates-run"),
    path("duplicates/<int:pk>/resolve/", DuplicateResolveView.as_view(), name="harvest-duplicate-resolve"),
    path("duplicates/bulk-resolve/", DuplicateBulkResolveView.as_view(), name="harvest-duplicate-bulk-resolve"),
    # Engine Config — runtime tuning knobs (concurrency, rate limit, stagger)
    path("engine/", EngineConfigView.as_view(), name="harvest-engine-config"),
    # Vet Gate Config — sync gate thresholds and domain blocklist
    path("vet-gate/", VetGateConfigView.as_view(), name="harvest-vet-gate-config"),
    path("vet-gate/preview/", VetGatePreviewView.as_view(), name="harvest-vet-gate-preview"),
    # Role routing rules — GUI-editable JobDomain pattern registry
    path("job-domains/", JobDomainListView.as_view(), name="harvest-job-domains"),
    path("job-domains/apply/", JobDomainApplyDownstreamView.as_view(), name="harvest-job-domain-apply"),
    path("job-domains/<int:pk>/quick/", JobDomainQuickUpdateView.as_view(), name="harvest-job-domain-quick"),
    path("job-domains/impact/", JobDomainImpactApiView.as_view(), name="harvest-job-domain-impact"),
    path("job-domains/new/", JobDomainCreateView.as_view(), name="harvest-job-domain-create"),
    path("job-domains/<int:pk>/edit/", JobDomainUpdateView.as_view(), name="harvest-job-domain-edit"),
    path("job-domains/<int:pk>/delete/", JobDomainDeleteView.as_view(), name="harvest-job-domain-delete"),
    path("job-domains/test/", JobDomainTestApiView.as_view(), name="harvest-job-domain-test"),
    path("role-categories/", SelectiveRoleCategoryListView.as_view(), name="harvest-role-categories"),
    path("role-categories/phrase/", views.RolePhraseQuickAddView.as_view(), name="harvest-role-phrase-edit"),
    path("role-categories/phrase-impact/", views.RolePhraseImpactView.as_view(), name="harvest-role-phrase-impact"),
    path("role-categories/apply/", views.RoleReclassifyApplyView.as_view(), name="harvest-role-apply"),
    path("role-categories/new/", SelectiveRoleCategoryCreateView.as_view(), name="harvest-role-category-create"),
    path("role-categories/<int:pk>/edit/", SelectiveRoleCategoryUpdateView.as_view(), name="harvest-role-category-edit"),
    path("role-categories/api/title-test/", SelectiveTitleTestApiView.as_view(), name="harvest-title-test-api"),
    path("skipped-titles/", SkippedTitlesAuditView.as_view(), name="harvest-skipped-titles"),
    path("skipped-titles/<int:pk>/recover/", SkippedTitleRecoverView.as_view(), name="harvest-skipped-title-recover"),
    path("zero-tech-companies/", ZeroTechCompaniesView.as_view(), name="harvest-zero-tech-companies"),
    path("filter-snapshots/", FilterSnapshotListView.as_view(), name="harvest-filter-snapshots"),
    path("filter-snapshots/<int:pk>/", FilterSnapshotDetailView.as_view(), name="harvest-filter-snapshot-detail"),
    # Job Jarvis — paste-any-URL ingestion
    path("jarvis/", JarvisView.as_view(), name="harvest-jarvis"),
    path("jarvis/status/", JarvisStatusView.as_view(), name="harvest-jarvis-status"),
    path("jarvis/approve/", JarvisApproveView.as_view(), name="harvest-jarvis-approve"),
    path("jarvis/fetch-all/", JarvisFetchCompanyJobsView.as_view(), name="harvest-jarvis-fetch-all"),
    path("jarvis/fetch-all/progress/", JarvisFetchProgressView.as_view(), name="harvest-jarvis-fetch-all-progress"),
    path("jarvis/fetch-all/progress/api/", JarvisFetchProgressApiView.as_view(), name="harvest-jarvis-fetch-all-progress-api"),
    path("jarvis/rescrape/", JarvisReScrapeView.as_view(), name="harvest-jarvis-rescrape"),
]
